const TestController = require('./controllers/TestController')
const AuthenticationController = require('./controllers/AuthenticationController')
const BuyersController = require('./controllers/BuyersController')
const PricesController = require('./controllers/PricesController')
const ItemController = require('./controllers/ItemController')
const ProductsController = require('./controllers/ProductsController')
const InvoiceController = require('./controllers/InvoiceController')

module.exports = (app) => {
  app.get('/api/register', TestController.register)
  app.post('/api/login', TestController.login)
  app.get('/api/buyers', AuthenticationController.authenticate, BuyersController.getBuyers)
  app.post('/api/buyers', BuyersController.addBuyer)
  app.put('/api/buyers', BuyersController.updateBuyers)
  app.get('/api/prices/:buyId', PricesController.getPrices)
  app.post('/api/items', ItemController.addItems)
  app.delete('/api/items', ItemController.deleteItem)
  app.get('/api/products', ProductsController.getProducts)
  app.post('/api/products', ProductsController.updateProducts)
  app.put('/api/invoices', InvoiceController.getInvoice)
  app.post('/api/invoices', InvoiceController.addInvoice)
  app.post('/api/close', InvoiceController.closeInvoice)
  app.patch('/api/history', InvoiceController.getHistory)
}
